<?php
/**
 * InlineResponse20026PackageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20026PackageTest Class Doc Comment
 *
 * @category    Class
 * @description Информация о пакете
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20026PackageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20026Package"
     */
    public function testInlineResponse20026Package()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "tour_id"
     */
    public function testPropertyTourId()
    {
    }

    /**
     * Test attribute "adults_count"
     */
    public function testPropertyAdultsCount()
    {
    }

    /**
     * Test attribute "kids_count"
     */
    public function testPropertyKidsCount()
    {
    }

    /**
     * Test attribute "kids_ages"
     */
    public function testPropertyKidsAges()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "arrival_date"
     */
    public function testPropertyArrivalDate()
    {
    }

    /**
     * Test attribute "nights_count"
     */
    public function testPropertyNightsCount()
    {
    }

    /**
     * Test attribute "pansion"
     */
    public function testPropertyPansion()
    {
    }

    /**
     * Test attribute "region_name"
     */
    public function testPropertyRegionName()
    {
    }

    /**
     * Test attribute "transfer"
     */
    public function testPropertyTransfer()
    {
    }

    /**
     * Test attribute "room_type"
     */
    public function testPropertyRoomType()
    {
    }

    /**
     * Test attribute "net_price"
     */
    public function testPropertyNetPrice()
    {
    }

    /**
     * Test attribute "fuel_charge"
     */
    public function testPropertyFuelCharge()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "dates_info"
     */
    public function testPropertyDatesInfo()
    {
    }

    /**
     * Test attribute "pansion_description"
     */
    public function testPropertyPansionDescription()
    {
    }

    /**
     * Test attribute "pansion_original"
     */
    public function testPropertyPansionOriginal()
    {
    }

    /**
     * Test attribute "operator"
     */
    public function testPropertyOperator()
    {
    }

    /**
     * Test attribute "departure"
     */
    public function testPropertyDeparture()
    {
    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "ordered"
     */
    public function testPropertyOrdered()
    {
    }

    /**
     * Test attribute "search_request"
     */
    public function testPropertySearchRequest()
    {
    }

    /**
     * Test attribute "instant_confirm"
     */
    public function testPropertyInstantConfirm()
    {
    }

    /**
     * Test attribute "medical_insurance"
     */
    public function testPropertyMedicalInsurance()
    {
    }

    /**
     * Test attribute "misc_data"
     */
    public function testPropertyMiscData()
    {
    }

    /**
     * Test attribute "manual"
     */
    public function testPropertyManual()
    {
    }

    /**
     * Test attribute "previous_price"
     */
    public function testPropertyPreviousPrice()
    {
    }

    /**
     * Test attribute "cheap_type"
     */
    public function testPropertyCheapType()
    {
    }

    /**
     * Test attribute "booking_url"
     */
    public function testPropertyBookingUrl()
    {
    }

    /**
     * Test attribute "actualization_url"
     */
    public function testPropertyActualizationUrl()
    {
    }

    /**
     * Test attribute "room_info"
     */
    public function testPropertyRoomInfo()
    {
    }

    /**
     * Test attribute "extras"
     */
    public function testPropertyExtras()
    {
    }

    /**
     * Test attribute "cancellation_policy"
     */
    public function testPropertyCancellationPolicy()
    {
    }

    /**
     * Test attribute "insurable"
     */
    public function testPropertyInsurable()
    {
    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {
    }

    /**
     * Test attribute "notices"
     */
    public function testPropertyNotices()
    {
    }

    /**
     * Test attribute "labels"
     */
    public function testPropertyLabels()
    {
    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {
    }

    /**
     * Test attribute "confirmability_index"
     */
    public function testPropertyConfirmabilityIndex()
    {
    }

    /**
     * Test attribute "hotel"
     */
    public function testPropertyHotel()
    {
    }
}
