<?php
/**
 * InlineResponse2002FiltersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002FiltersTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002Filters
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002FiltersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2002Filters"
     */
    public function testInlineResponse2002Filters()
    {
    }

    /**
     * Test attribute "meals"
     */
    public function testPropertyMeals()
    {
    }

    /**
     * Test attribute "regions"
     */
    public function testPropertyRegions()
    {
    }

    /**
     * Test attribute "countries"
     */
    public function testPropertyCountries()
    {
    }

    /**
     * Test attribute "stars"
     */
    public function testPropertyStars()
    {
    }

    /**
     * Test attribute "operators"
     */
    public function testPropertyOperators()
    {
    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {
    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {
    }

    /**
     * Test attribute "beach_surface"
     */
    public function testPropertyBeachSurface()
    {
    }

    /**
     * Test attribute "beach_type"
     */
    public function testPropertyBeachType()
    {
    }

    /**
     * Test attribute "wifi"
     */
    public function testPropertyWifi()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "ski_distance"
     */
    public function testPropertySkiDistance()
    {
    }

    /**
     * Test attribute "prices"
     */
    public function testPropertyPrices()
    {
    }

    /**
     * Test attribute "lt_extras"
     */
    public function testPropertyLtExtras()
    {
    }

    /**
     * Test attribute "instant_confirm"
     */
    public function testPropertyInstantConfirm()
    {
    }

    /**
     * Test attribute "fitness"
     */
    public function testPropertyFitness()
    {
    }

    /**
     * Test attribute "aquapark"
     */
    public function testPropertyAquapark()
    {
    }

    /**
     * Test attribute "nanny"
     */
    public function testPropertyNanny()
    {
    }

    /**
     * Test attribute "kids_menu"
     */
    public function testPropertyKidsMenu()
    {
    }

    /**
     * Test attribute "kids_club"
     */
    public function testPropertyKidsClub()
    {
    }

    /**
     * Test attribute "kids_pool"
     */
    public function testPropertyKidsPool()
    {
    }

    /**
     * Test attribute "pool"
     */
    public function testPropertyPool()
    {
    }

    /**
     * Test attribute "heated_pool"
     */
    public function testPropertyHeatedPool()
    {
    }

    /**
     * Test attribute "aircon"
     */
    public function testPropertyAircon()
    {
    }

    /**
     * Test attribute "parking"
     */
    public function testPropertyParking()
    {
    }

    /**
     * Test attribute "massage"
     */
    public function testPropertyMassage()
    {
    }

    /**
     * Test attribute "thermal_fun"
     */
    public function testPropertyThermalFun()
    {
    }

    /**
     * Test attribute "bar"
     */
    public function testPropertyBar()
    {
    }

    /**
     * Test attribute "ski_in"
     */
    public function testPropertySkiIn()
    {
    }

    /**
     * Test attribute "ski_out"
     */
    public function testPropertySkiOut()
    {
    }

    /**
     * Test attribute "free_cancel"
     */
    public function testPropertyFreeCancel()
    {
    }

    /**
     * Test attribute "indoor_pool"
     */
    public function testPropertyIndoorPool()
    {
    }

    /**
     * Test attribute "no_single_men"
     */
    public function testPropertyNoSingleMen()
    {
    }

    /**
     * Test attribute "payment_benefits"
     */
    public function testPropertyPaymentBenefits()
    {
    }

    /**
     * Test attribute "travel_benefits"
     */
    public function testPropertyTravelBenefits()
    {
    }

    /**
     * Test attribute "adults_only"
     */
    public function testPropertyAdultsOnly()
    {
    }
}
