<?php
/**
 * InlineResponse20011FeaturesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20011FeaturesTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse20011Features
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20011FeaturesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20011Features"
     */
    public function testInlineResponse20011Features()
    {
    }

    /**
     * Test attribute "construction_year"
     */
    public function testPropertyConstructionYear()
    {
    }

    /**
     * Test attribute "renovation_year"
     */
    public function testPropertyRenovationYear()
    {
    }

    /**
     * Test attribute "airport_distance"
     */
    public function testPropertyAirportDistance()
    {
    }

    /**
     * Test attribute "beach_distance"
     */
    public function testPropertyBeachDistance()
    {
    }

    /**
     * Test attribute "beach_size"
     */
    public function testPropertyBeachSize()
    {
    }

    /**
     * Test attribute "beach_type"
     */
    public function testPropertyBeachType()
    {
    }

    /**
     * Test attribute "beach_surface"
     */
    public function testPropertyBeachSurface()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {
    }

    /**
     * Test attribute "wi_fi"
     */
    public function testPropertyWiFi()
    {
    }

    /**
     * Test attribute "ski_lift_distance"
     */
    public function testPropertySkiLiftDistance()
    {
    }

    /**
     * Test attribute "ski_in"
     */
    public function testPropertySkiIn()
    {
    }

    /**
     * Test attribute "ski_out"
     */
    public function testPropertySkiOut()
    {
    }

    /**
     * Test attribute "fitness"
     */
    public function testPropertyFitness()
    {
    }

    /**
     * Test attribute "aquapark"
     */
    public function testPropertyAquapark()
    {
    }

    /**
     * Test attribute "nanny"
     */
    public function testPropertyNanny()
    {
    }

    /**
     * Test attribute "kids_menu"
     */
    public function testPropertyKidsMenu()
    {
    }

    /**
     * Test attribute "warm_pool"
     */
    public function testPropertyWarmPool()
    {
    }

    /**
     * Test attribute "kids_club"
     */
    public function testPropertyKidsClub()
    {
    }

    /**
     * Test attribute "aircon"
     */
    public function testPropertyAircon()
    {
    }

    /**
     * Test attribute "parking"
     */
    public function testPropertyParking()
    {
    }
}
