<?php
/**
 * InlineResponse2002ExtrasTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002ExtrasTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002Extras
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2002ExtrasTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2002Extras"
     */
    public function testInlineResponse2002Extras()
    {
    }

    /**
     * Test attribute "suggested"
     */
    public function testPropertySuggested()
    {
    }

    /**
     * Test attribute "instant_confirm"
     */
    public function testPropertyInstantConfirm()
    {
    }

    /**
     * Test attribute "early_booking"
     */
    public function testPropertyEarlyBooking()
    {
    }

    /**
     * Test attribute "high_priority"
     */
    public function testPropertyHighPriority()
    {
    }

    /**
     * Test attribute "cheap"
     */
    public function testPropertyCheap()
    {
    }

    /**
     * Test attribute "cheap_type"
     */
    public function testPropertyCheapType()
    {
    }

    /**
     * Test attribute "previous_price"
     */
    public function testPropertyPreviousPrice()
    {
    }
}
