<?php
/**
 * InlineResponse20024RoomInfoImagesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse20024RoomInfoImagesTest Class Doc Comment
 *
 * @category    Class
 * @description Информация об изображение номера
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse20024RoomInfoImagesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse20024RoomInfoImages"
     */
    public function testInlineResponse20024RoomInfoImages()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "x100x110"
     */
    public function testPropertyX100x110()
    {
    }

    /**
     * Test attribute "x150x110"
     */
    public function testPropertyX150x110()
    {
    }

    /**
     * Test attribute "x260x150"
     */
    public function testPropertyX260x150()
    {
    }

    /**
     * Test attribute "x900x380"
     */
    public function testPropertyX900x380()
    {
    }

    /**
     * Test attribute "x900"
     */
    public function testPropertyX900()
    {
    }
}
