<?php
/**
 * SearchApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PAPI
 *
 * <center>                         <img src=\"https://img.cdn.level.travel/assets/logo/vector-58a947fae5d47fa53329be95ff9cff853e8889f70ac61fc2d2b6572a5998330e.svg\">                         <br><br>                         <h1>Партнёрская документация Open API</h1>                       </center>
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SearchApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SearchApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for searchEnqueueGet
     *
     * Добавление поискового запроса в очередь.
     *
     */
    public function testSearchEnqueueGet()
    {
    }

    /**
     * Test case for searchGetGroupedHotelsGet
     *
     * Метод получения списка отелей.
     *
     */
    public function testSearchGetGroupedHotelsGet()
    {
    }

    /**
     * Test case for searchHotelRoomsGet
     *
     * Метод получения комнат в отеле.
     *
     */
    public function testSearchHotelRoomsGet()
    {
    }

    /**
     * Test case for searchLandGet
     *
     * Получить поисковые параметры и ссылку на поиск.
     *
     */
    public function testSearchLandGet()
    {
    }

    /**
     * Test case for searchStatusGet
     *
     * Статус поискового запроса.
     *
     */
    public function testSearchStatusGet()
    {
    }
}
